# Generated by Django 4.2.9 on 2024-01-07 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('relacion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='prooveedor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='relacion.prooveedor'),
        ),
        migrations.AddField(
            model_name='prooveedor',
            name='pais',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='relacion.pais'),
        ),
    ]
