# Generated by Django 4.2.9 on 2024-01-06 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=1000)),
                ('codigo', models.TextField(blank=True)),
                ('precio', models.TextField(blank=True)),
                ('cantidad', models.TextField(blank=True)),
                ('marca', models.TextField(blank=True)),
            ],
        ),
    ]
